// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg-ElXp15YOhFCrI19G2K-YcGZJJAAnCU',
    appId: '1:832617788878:web:502cb23dc80c7e003b679f',
    messagingSenderId: '832617788878',
    projectId: 'vip-client-manager',
    authDomain: 'vip-client-manager.firebaseapp.com',
    storageBucket: 'vip-client-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOk5iXMvE4W77XWtC_HQaoYxGrTKndme8',
    appId: '1:832617788878:android:727f45ff46a400a03b679f',
    messagingSenderId: '832617788878',
    projectId: 'vip-client-manager',
    storageBucket: 'vip-client-manager.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjAMP1P2ylfz69OvTM2uvSYRhMvO60i9g',
    appId: '1:832617788878:ios:23662f2e4f6017cf3b679f',
    messagingSenderId: '832617788878',
    projectId: 'vip-client-manager',
    storageBucket: 'vip-client-manager.firebasestorage.app',
    iosBundleId: 'kz.drtoitayev.crm',
  );
}
